import { mockIp, mockReqId } from '../utils/mock';

export function genCartGroupData() {
  const resp = {
    data: {
      isNotEmpty: true,
      storeGoods: [
        {
          storeId: '1000',
          storeName: '云Mall深圳旗舰店',
          storeStatus: 1,
          totalDiscountSalePrice: '9990',
          promotionGoodsList: [
            {
              title: '满减满折回归',
              promotionCode: 'MERCHANT',
              promotionSubCode: 'MYJ',
              promotionId: '159174555838121985',
              tagText: ['满100元减99.9元'],
              promotionStatus: 3,
              tag: '满减',
              description: '满100元减99.9元,已减99.9元',
              doorSillRemain: null,
              isNeedAddOnShop: 0,
              goodsPromotionList: [
                {
                  uid: '88888888205468',
                  saasId: '88888888',
                  storeId: '1000',
                  spuId: '12',
                  skuId: '135691622',
                  isSelected: 1,
                  thumb: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=400&h=400&fit=crop',
                  title: '杰克丹尼 田纳西威士忌 700ml 美国进口 洋酒',
                  primaryImage: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=400&h=400&fit=crop',
                  quantity: 1,
                  stockStatus: true,
                  stockQuantity: 3,
                  price: '9900',
                  originPrice: '16900',
                  tagPrice: null,
                  titlePrefixTags: [{ text: '新品' }, { text: '火爆' }],
                  roomId: null,
                  specInfo: [
                    {
                      specTitle: '颜色',
                      specValue: '经典白',
                    },
                    {
                      specTitle: '类型',
                      specValue: '经典套装',
                    },
                  ],
                  joinCartTime: '2020-06-29T07:55:40.000+0000',
                  available: 1,
                  putOnSale: 1,
                  etitle: null,
                },
                {
                  uid: '88888888205468',
                  saasId: '88888888',
                  storeId: '1000',
                  spuId: '18',
                  skuId: '135681631',
                  isSelected: 1,
                  thumb: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=400&fit=crop',
                  title: '贵州茅台酒 飞天茅台 53度 酱香型白酒 500ml',
                  primaryImage: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=400&fit=crop',
                  quantity: 1,
                  stockStatus: true,
                  stockQuantity: 177,
                  price: '29800',
                  originPrice: '40000',
                  tagPrice: null,
                  titlePrefixTags: null,
                  roomId: null,
                  specInfo: [
                    {
                      specTitle: '颜色',
                      specValue: '米色荷叶边',
                    },
                    {
                      specTitle: '尺码',
                      specValue: 'M',
                    },
                  ],
                  joinCartTime: '2020-06-29T07:55:27.000+0000',
                  available: 1,
                  putOnSale: 1,
                  etitle: null,
                },
                {
                  uid: '88888888205468',
                  saasId: '88888888',
                  storeId: '1000',
                  spuId: '13',
                  skuId: '135698362',
                  isSelected: 1,
                  thumb: 'https://images.unsplash.com/photo-1571613316887-6f8d5cbf7ef7?w=400&h=400&fit=crop',
                  title: '奔富 洛神山庄 设拉子干红葡萄酒 750ml 澳洲进口',
                  primaryImage: 'https://images.unsplash.com/photo-1571613316887-6f8d5cbf7ef7?w=400&h=400&fit=crop',
                  quantity: 13,
                  stockStatus: true,
                  stockQuantity: 9,
                  price: '29900',
                  originPrice: '0',
                  tagPrice: null,
                  titlePrefixTags: [{ text: '火爆' }],
                  roomId: null,
                  specInfo: [
                    {
                      specTitle: '颜色',
                      specValue: '浅灰色',
                    },
                    {
                      specTitle: '尺码',
                      specValue: 'M',
                    },
                  ],
                  joinCartTime: '2020-06-29T07:54:43.000+0000',
                  available: 1,
                  putOnSale: 1,
                  etitle: null,
                },
                {
                  uid: '88888888205468',
                  saasId: '88888888',
                  storeId: '1000',
                  spuId: '7',
                  skuId: '135681625',
                  isSelected: 1,
                  thumb: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=400&h=400&fit=crop',
                  title: '元气森林 苏打气泡水 白桃味 480ml*15瓶 整箱',
                  primaryImage: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=400&h=400&fit=crop',
                  quantity: 1,
                  stockStatus: true,
                  stockQuantity: 0,
                  price: '29900',
                  originPrice: '29900',
                  tagPrice: null,
                  titlePrefixTags: null,
                  roomId: null,
                  specInfo: [
                    {
                      specTitle: '颜色',
                      specValue: '奶黄色',
                    },
                    {
                      specTitle: '数量',
                      specValue: '六件套',
                    },
                  ],
                  joinCartTime: '2020-06-29T07:55:00.000+0000',
                  available: 1,
                  putOnSale: 1,
                  etitle: null,
                },
              ],
              lastJoinTime: '2020-06-29T07:55:40.000+0000',
            },
            {
              title: null,
              promotionCode: 'EMPTY_PROMOTION',
              promotionSubCode: null,
              promotionId: null,
              tagText: null,
              promotionStatus: null,
              tag: null,
              description: null,
              doorSillRemain: null,
              isNeedAddOnShop: 0,
              goodsPromotionList: [
                {
                  uid: '88888888205468',
                  saasId: '88888888',
                  storeId: '1000',
                  spuId: '11',
                  skuId: '135691629',
                  isSelected: 0,
                  thumb: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&h=400&fit=crop',
                  title: '拉菲传奇波尔多 干红葡萄酒 750ml 法国进口',
                  primaryImage: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&h=400&fit=crop',
                  quantity: 1,
                  stockStatus: false,
                  stockQuantity: 0,
                  price: '25900',
                  originPrice: '39900',
                  tagPrice: null,
                  tagText: null,
                  roomId: null,
                  specInfo: [
                    {
                      specTitle: '颜色',
                      specValue: '军绿色',
                    },
                    {
                      specTitle: '尺码',
                      specValue: 'S',
                    },
                  ],
                  joinCartTime: '2020-04-24T06:26:48.000+0000',
                  available: 1,
                  putOnSale: 1,
                  etitle: null,
                },
                {
                  uid: '88888888205468',
                  saasId: '88888888',
                  storeId: '1000',
                  spuId: '5',
                  skuId: '135691635',
                  isSelected: 0,
                  thumb: 'https://images.unsplash.com/photo-1574006852726-31d0ae47b93e?w=400&h=400&fit=crop',
                  title: '绝对伏特加 原味 700ml 瑞典进口 经典洋酒',
                  primaryImage: 'https://images.unsplash.com/photo-1574006852726-31d0ae47b93e?w=400&h=400&fit=crop',
                  quantity: 1,
                  stockStatus: true,
                  stockQuantity: 96,
                  price: '29000',
                  originPrice: '29900',
                  tagPrice: null,
                  tagText: null,
                  roomId: null,
                  specInfo: [
                    {
                      specTitle: '颜色',
                      specValue: '黑色',
                    },
                    {
                      specTitle: '类型',
                      specValue: '简约款',
                    },
                  ],
                  joinCartTime: '2020-06-29T07:55:17.000+0000',
                  available: 1,
                  putOnSale: 1,
                  etitle: null,
                },
              ],
              lastJoinTime: null,
            },
          ],
          lastJoinTime: '2020-06-29T07:55:40.000+0000',
          postageFreePromotionVo: {
            title: null,
            promotionCode: null,
            promotionSubCode: null,
            promotionId: null,
            tagText: null,
            promotionStatus: null,
            tag: null,
            description: null,
            doorSillRemain: null,
            isNeedAddOnShop: 0,
          },
        },
      ],
      invalidGoodItems: [
        {
          uid: '88888888205468',
          saasId: '88888888',
          storeId: '1000',
          spuId: '1',
          skuId: '135691631',
          isSelected: 1,
          thumb: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&h=400&fit=crop',
          title: '五粮液 普五 52度 浓香型白酒 500ml 经典款',
          primaryImage: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&h=400&fit=crop',
          quantity: 8,
          stockStatus: true,
          stockQuantity: 177,
          price: '26900',
          originPrice: '31900',
          tagPrice: null,
          tagText: null,
          roomId: null,
          specInfo: [
            {
              specTitle: '颜色',
              specValue: '白色',
            },
            {
              specTitle: '尺码',
              specValue: 'S',
            },
          ],
          joinCartTime: '2020-04-28T04:03:59.000+0000',
          available: 1,
          putOnSale: 1,
          etitle: null,
        },
      ],
      isAllSelected: false,
      selectedGoodsCount: 16,
      totalAmount: '179997',
      totalDiscountAmount: '110000',
    },
    code: 'Success',
    msg: null,
    requestId: mockReqId(),
    clientIp: mockIp(),
    rt: 269,
    success: true,
  };
  return resp;
}
